{% set version = "0.1.0" %}

package:
  name: gaia
  version: {{ version }}

source:
  git_url: https://github.com/OpenDataAnalytics/gaia
  git_branch: master

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - six
    - requests
    - shapely
    - geopandas
    - pillow

test:
  imports:
    - gaia
  files:
    - test_data/test.cpg
    - test_data/test.dbf
    - test_data/test.shp
    - test_data/test.shx

about:
  home: https://github.com/OpenDataAnalytics/gaia
  license: Apache V2
  summary: 'Geospatial analytics library'

extra:
  recipe-maintainers:
    - kitware
