{% set version = "0.1.0" %}

package:
  name: gaia
  version: {{ version }}

source:
  git_url: https://github.com/OpenDataAnalytics/gaia
  git_branch: master

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - six
    - requests
    - shapely
    - pillow
    - geopandas
    - gdal 2.2.3
    - pdal 1.6
    - celery >=3.1.20
    - psycopg2 >=2.6.1
    - geoalchemy2 >=0.2.6

test:
  files:
    - test_data/test.cpg
    - test_data/test.dbf
    - test_data/test.shp
    - test_data/test.shx

about:
  home: https://github.com/OpenDataAnalytics/gaia
  license: Apache V2
  summary: 'Geospatial analytics library'

extra:
  recipe-maintainers:
    - kitware
